### ISSUE TITLE
Copyright Infringement 

### ISSUE THREAD

**Issue by wltjr** [vapier/vapier.github.io#1]
vapier™ and Mike Frysinger™ are trademarks of William Thomson™©℗.... Mike get at me so we can discuss legal options! :)

https://look-at-my.horse/

**Comment by wltjr** [comment]
[10 Hour Loop](https://www.youtube.com/watch?v=_8mZX4xu2P8) :: Look at my horse

**Comment by vapier** [comment]
you can't copyright a trademark
